# make CTRL + A 'the binding'
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1

# mouse does stuff
set -g mouse on

set -g history-limit 10000

set -g set-clipboard on

# set tmux to vi mode
setw -g mode-keys vi

# send copied content to Mac clipboard
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"

# open new panes in same dir
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
