export JAVA_HOME=$(/usr/libexec/java_home -v 21)

export PATH=$(brew --prefix openssh)/bin:$PATH

alias claude-sr='CLAUDE_CONFIG_DIR=~/.claude-sports-reference claude'

alias claude-personal='CLAUDE_CONFIG_DIR=$HOME/.claude claude'

# alias ls='ls --color=auto'

